spring.application.name=ss14

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ss14javaservice?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=quanglienha

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

cloudinary.cloud_name=dfireq2op
cloudinary.api_key=516693126687581
cloudinary.api_secret=L4E20dGNttEQqtcIGALbKY_FKIw