spring.application.name=ss9

#datasource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ss9javaservice?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=quanglienha

#jpa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=9999

#cloudinary
cloud_name = dfireq2op
api_key = 516693126687581
api_secret = L4E20dGNttEQqtcIGALbKY_FKIw

logging.level.root=DEBUG

logging.file.name=logs/app.log
logging.level.com.ra.ss9=INFO
logging.file.path=logs
spring.output.ansi.enabled=ALWAYS
